src/MakeupStudio/Models/Orders/AppointMeetingModel.cs
using System;

namespace MakeupStudio.Models.Orders
{
    /// <summary>
    /// Модель для страницы приема заявки
    /// </summary>
    public class AppointMeetingModel
    {
        /// <summary>
        /// Id заявки
        /// </summary>
        public long OrderId { get; set; }

        /// <summary>
        /// Дата, когда оставили заявку (UTC)
        /// </summary>
        public DateTime CreatedDate { get; set; }

        /// <summary>
        /// Имя клиента
        /// </summary>
        public string ClientName { get; set; }

        /// <summary>
        /// Телефон клиента
        /// </summary>
        public string ClientPhone { get; set; }

        /// <summary>
        /// Комментарий клиента
        /// </summary>
        public string ClientComment { get; set; }
    }
}

src/MakeupStudio/Models/Orders/CreateOrderModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using MakeupStudio.Common.Constants;
using MakeupStudio.Core.Entities;

namespace MakeupStudio.Models.Orders
{
    /// <summary>
    /// Модель создания заказа
    /// </summary>
    public class CreateOrderModel
    {
        /// <summary>
        /// Имя клиента
        /// </summary>
        [Required(ErrorMessage = "Заполните имя клиента", AllowEmptyStrings = false)]
        [MaxLength(Company.NAME_MAX_LENGTH, ErrorMessage = "Слишком длинное имя")]
        [RegularExpression(RegexConstants.NAME, ErrorMessage = ValidationErrors.NAME_INCORRECT_FORMAT)]
        public string ClientName { get; set; }

        /// <summary>
        /// Телефон клиента
        /// </summary>
        [Required(ErrorMessage = "Укажите телефон клиента", AllowEmptyStrings = false)]
        [RegularExpression(RegexConstants.PHONE, ErrorMessage = ValidationErrors.PHONE_INCORRECT_FORMAT)]
        public string ClientPhone { get; set; }

        /// <summary>
        /// Время, на которое назначен прием для клиента (ко скольки клиент должен подойти) (в UTC)
        /// </summary>
        public DateTime AppointedTime { get; set; }

        /// <summary>
        /// Комментарий мастера
        /// </summary>
        [MaxLength(Order.MASTER_COMMENT_MAX_LENGTH, ErrorMessage = "Максимальная длина комментария {0} символов")]
        [RegularExpression(RegexConstants.COMMENT, ErrorMessage = ValidationErrors.COMMENT_INCORRECT_FORMAT)]
        public string MasterComment { get; set; }
    }
}

src/MakeupStudio/Models/Orders/EditOrderModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using MakeupStudio.Common.Constants;
using MakeupStudio.Core.Entities;

namespace MakeupStudio.Models.Orders
{
    /// <summary>
    /// Модель для редактирования заказа
    /// </summary>
    public class EditOrderModel
    {
        public long OrderId { get; set; }

        /// <summary>
        /// Дата, когда оставили заявку (UTC)
        /// </summary>
        public DateTime CreatedDate { get; set; }

        /// <summary>
        /// Имя клиента
        /// </summary>
        [Required(ErrorMessage = "Заполните имя клиента", AllowEmptyStrings = false)]
        [MaxLength(Company.NAME_MAX_LENGTH, ErrorMessage = "Слишком длинное имя")]
        [RegularExpression(RegexConstants.NAME, ErrorMessage = ValidationErrors.NAME_INCORRECT_FORMAT)]
        public string ClientName { get; set; }

        /// <summary>
        /// Телефон клиента
        /// </summary>
        [Required(ErrorMessage = "Укажите телефон", AllowEmptyStrings = false)]
        [RegularExpression(RegexConstants.PHONE, ErrorMessage = ValidationErrors.PHONE_INCORRECT_FORMAT)]
        public string ClientPhone { get; set; }

        /// <summary>
        /// Комментарий клиента
        /// </summary>
        public string ClientComment { get; set; }

        /// <summary>
        /// Время, на которое назначен прием для клиента (ко скольки клиент должен подойти) (в UTC)
        /// </summary>
        public DateTime AppointedTime { get; set; }

        /// <summary>
        /// Комментарий мастера
        /// </summary>
        [MaxLength(Order.MASTER_COMMENT_MAX_LENGTH, ErrorMessage = "Максимальная длина комментария {0} символов")]
        [RegularExpression(RegexConstants.COMMENT, ErrorMessage = ValidationErrors.COMMENT_INCORRECT_FORMAT)]
        public string MasterComment { get; set; }
    }
}

src/MakeupStudio/Controllers/OrdersController.cs
using System.Threading.Tasks;
using System.Web.Helpers;
using System.Web.Mvc;
using MakeupStudio.Attributes;
using MakeupStudio.Business.Commands;
using MakeupStudio.Common.Extensions;
using MakeupStudio.Core.Services;
using MakeupStudio.Extensions;
using MakeupStudio.ModelBuilders.Order;
using MakeupStudio.Models.Orders;
using MakeupStudio.Requests.Orders;
using MakeupStudio.Responses;

namespace MakeupStudio.Controllers
{
    /// <summary>
    /// Контроллер для работы с заявками и заказами
    /// </summary>
    [Authorize]
    public class OrdersController : BaseController
    {
        private readonly IOrderService _orderService;

        public OrdersController(IOrderService orderService)
        {
            _orderService = orderService;
        }



        #region Заявки

        /// <summary>
        /// Страница с необработанными заявками
        /// </summary>
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Ajax метод для получения списка заявок
        /// </summary>
        [HttpGet]
        public async Task<JsonResult> GetNotAcceptedOrders()
        {
            var model = await _orderService.GetNotAcceptedOrders(CurrentUser.CompanyId);
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Ajax метод для удаления заказа
        /// </summary>
        [HttpPost]
        public async Task<JsonResult> DeleteOrder(int orderId, bool showMessage = false)
        {
            var commandArgs = CreateCommandArgs<DeleteOrderCommandArgs>();
            commandArgs.OrderId = orderId;
            var commandResult = await ExecuteCommand<DeleteOrderCommandArgs, EmptyCommandResult>(commandArgs);

            if (showMessage && commandResult.IsSuccess)
                SetSuccessMessage("Заказ успешно удален");

            return Json(commandResult.ConverToResponse<EmptyResponse>());
        }

        /// <summary>
        /// Метод для назначения приема клиента
        /// </summary>
        [HttpGet]
        public async Task<ActionResult> AppointMeeting(long orderId)
        {
            var modelBuilder = new AppointMeetingModelBuilder(_orderService);
            var model = await modelBuilder.Build(orderId, CurrentUser);

            if (model == null)
                return RedirectToAction("Index");

            return View(model);
        }

        /// <summary>
        /// Метод сохранения для страницы назначения приема клиента
        /// </summary>
        [HttpPost, ValidateRequest]
        public async Task<JsonResult> AppointMeeting(AppointMeetingRequest request)
        {
            var args = CreateCommandArgs<AppointMeetingCommandArgs>();
            args.AppointedTime = request.AppointedTime.ToUtc();
            args.MasterComment = request.MasterComment;
            args.OrderId = request.OrderId;

            var commandResult = await ExecuteCommand<AppointMeetingCommandArgs, EmptyCommandResult>(args);

            if (commandResult.IsSuccess)
                SetSuccessMessage(@"Заявка успешно принята. Она перемещена в раздел ""Заказы""");

            return Json(commandResult.ConverToResponse<EmptyResponse>());
        }

        #endregion



        #region Заказы

        /// <summary>
        /// Страница заказов
        /// </summary>
        [HttpGet]
        public async Task<ActionResult> UpcomingOrders()
        {
            var orders = await _orderService.GetAcceptedOrders(CurrentUser.CompanyId);
            return View(orders);
        }

        /// <summary>
        /// Метод для помечания заказа как "Выполнено"
        /// </summary>
        [HttpPost]
        public async Task<JsonResult> FinishOrder(long orderId)
        {
            var args = CreateCommandArgs<FinishOrderCommandArgs>();
            args.OrderId = orderId;
            var commandResult = await ExecuteCommand<FinishOrderCommandArgs, EmptyCommandResult>(args);

            if(commandResult.IsSuccess)
                SetSuccessMessage("Заказ успешно помечен как выполненный");

            return Json(commandResult.ConverToResponse<EmptyResponse>());
        }

        /// <summary>
        /// Страница редактирования заказа
        /// </summary>
        [HttpGet]
        public async Task<ActionResult> Edit(long orderId)
        {
            var builder = new EditOrderModelBuilder(_orderService);
            var model = await builder.Build(CurrentUser, orderId);

            if (model == null)
                return RedirectToAction("UpcomingOrders");

            return View(model);
        }

        /// <summary>
        /// Ajax метод на изменение заказа
        /// </summary>
        [HttpPost, ValidateRequest]
        public async Task<JsonResult> Edit(EditOrderModel request)
        {
            var args = CreateCommandArgs<EditOrderCommandArgs>();
            args.OrderId = request.OrderId;
            args.AppointedTime = request.AppointedTime.ToUtc();
            args.ClientName = request.ClientName;
            args.ClientPhone = request.ClientPhone;
            args.MasterComment = request.MasterComment;

            var commandResult = await ExecuteCommand<EditOrderCommandArgs, EmptyCommandResult>(args);

            if(commandResult.IsSuccess)
                SetSuccessMessage("Заказ успешно изменен");

            return Json(commandResult.ConverToResponse<EmptyResponse>());
        }

        /// <summary>
        /// Страница создания заказа
        /// </summary>
        [HttpGet]
        public async Task<ActionResult> Create()
        {            
            return View(new CreateOrderModel());
        }

        /// <summary>
        /// Ajax метод на создание заказа
        /// </summary>
        [HttpPost, ValidateRequest]
        public async Task<JsonResult> Create(CreateOrderModel request)
        {
            var args = CreateCommandArgs<CreateOrderCommandArgs>();
            args.AppointedTime = request.AppointedTime.ToUtc();
            args.ClientName = request.ClientName;
            args.ClientPhone = request.ClientPhone;
            args.MasterComment = request.MasterComment;

            var commandResult = await ExecuteCommand<CreateOrderCommandArgs, EmptyCommandResult>(args);

            if(commandResult.IsSuccess)
                SetSuccessMessage("Заказ успешно создан");

            return Json(commandResult.ConverToResponse<EmptyResponse>());
        }

        #endregion
    }
}

src/MakeupStudio/Views/Orders/AppointMeeting.cshtml
@model MakeupStudio.Models.Orders.AppointMeetingModel
@{
    ViewBag.Title = "Назначение времени приема";
    Layout = "~/Views/Layouts/AdminLayout.cshtml";
}

@section styles
{
    @Styles.Render("~/bundles/styles/orders/assignappointment")
}

@section scripts
{
    @Scripts.Render("~/bundles/scripts/orders/assignappointment")
}

<a href="@Url.Action("Index", "Orders")" class="btn btn-info" style="margin-bottom: 20px;">
    <span class="glyphicon glyphicon-arrow-left"></span> Назад
</a>

<div style="max-width: 500px">
    @Html.Partial("~/Views/Partial/TempData.cshtml")
</div>

<div class="panel panel-default" style="max-width: 500px">
    <div class="panel-body">
        <form role="form">

            <input type="hidden" id="orderId" value="@Model.OrderId" />

            <div class="form-group">
                <label>Дата заявки</label>
                <input id="createdDate" disabled="disabled" type="text" class="form-control localdate" data-date="@Model.CreatedDate.ToString("O")"/>
                <p class="help-block">Время, когда клиент оставил заявку.</p>
            </div>

            <div class="form-group">
                <label>Имя клиента</label>
                <input disabled="disabled" type="text" class="form-control" value="@Model.ClientName"/>
            </div>

            <div class="form-group">
                <label>Телефон клиента</label>
                <input disabled="disabled" type="text" class="form-control" value="@Model.ClientPhone"/>
            </div>

            <div class="form-group">
                <label>Комментарий клиента</label>
                <textarea readonly="readonly" rows="3" type="text" class="form-control">@Model.ClientComment</textarea>
                <p class="help-block">Какие-либо пожелания клиента.</p>
            </div>

            <div class="form-group">
                <label>Дата и время записи</label>
                <div class="input-append date">
                    <input id="appointedTime" readonly="readonly" style="background-color: #ffffff" class="form-control" type="text">
                    <span class="add-on"><i class="icon-th"></i></span>
                </div>
            </div>

            <div class="form-group">
                <label>Ваш комментарий</label>
                <textarea id="masterComment" rows="3" type="text" class="form-control"></textarea>
                <p class="help-block">Не обязательно к заполнению. Видно только для Вас.</p>
            </div>

            <button href="#" type="button" class="btn btn-success" id="saveBtn">
                <span class="glyphicon glyphicon-ok"></span> Назначить
            </button>
        </form>
    </div>
</div>

src/MakeupStudio/Views/Orders/Create.cshtml
@model MakeupStudio.Models.Orders.CreateOrderModel

@{
    ViewBag.Title = "Создание заказа";
    Layout = "~/Views/Layouts/AdminLayout.cshtml";
}

@section scripts
{
    @Scripts.Render("~/bundles/scripts/orders/create")
}

@section styles
{
    @Styles.Render("~/bundles/styles/datepicker")
}

<a href="@Url.Action("UpcomingOrders", "Orders")" class="btn btn-info" style="margin-bottom: 20px;">
    <span class="glyphicon glyphicon-arrow-left"></span> Назад
</a>

<div style="max-width: 500px">
    @Html.Partial("~/Views/Partial/TempData.cshtml")
</div>

<div class="panel panel-default" style="max-width: 500px">
    <div class="panel-body">
        <form role="form">

            <div class="form-group">
                <label>Имя клиента</label>
                <input id="clientName" type="text" class="form-control" value="@Model.ClientName" />
            </div>

            <div class="form-group">
                <label>Телефон клиента</label>
                <input id="clientPhone" type="text" class="form-control" value="@Model.ClientPhone" />
            </div>

            <div class="form-group">
                <label>Дата и время записи</label>
                <div class="input-append date">
                    <input id="appointedTime" readonly="readonly" style="background-color: #ffffff" class="form-control" data-date="@Model.AppointedTime.ToString("O")" type="text">
                    <span class="add-on"><i class="icon-th"></i></span>
                </div>
            </div>

            <div class="form-group">
                <label>Ваш комментарий</label>
                <textarea id="masterComment" rows="3" type="text" class="form-control">@Model.MasterComment</textarea>
                <p class="help-block">Не обязательно к заполнению. Видно только для Вас.</p>
            </div>

            <button href="#" type="button" class="btn btn-success" id="saveBtn">
                <span class="glyphicon glyphicon-ok"></span> Создать
            </button>
        </form>
    </div>
</div>

src/MakeupStudio/Views/Orders/Edit.cshtml
@model MakeupStudio.Models.Orders.EditOrderModel
@{
    ViewBag.Title = "Редактирование заказа";
    Layout = "~/Views/Layouts/AdminLayout.cshtml";
}

@section scripts
{
    @Scripts.Render("~/bundles/scripts/orders/edit")
}

@section styles
{
    @Styles.Render("~/bundles/styles/datepicker")
}

<a href="@Url.Action("UpcomingOrders", "Orders")" class="btn btn-info" style="margin-bottom: 20px;">
    <span class="glyphicon glyphicon-arrow-left"></span> Назад
</a>

<div style="max-width: 500px">
    @Html.Partial("~/Views/Partial/TempData.cshtml")
</div>

<div class="panel panel-default" style="max-width: 500px">
    <div class="panel-body">
        <form role="form">

            <div class="form-group">
                <label>№ заказа</label>
                <input id="orderId" disabled="disabled" type="text" class="form-control" value="@Model.OrderId" />
            </div>

            <div class="form-group">
                <label>Дата создания заказа</label>
                <input id="createdDate" disabled="disabled" type="text" class="form-control localdate" data-date="@Model.CreatedDate.ToString("O")" />
                <p class="help-block">Время, когда клиент оставил заявку или когда Вы создали заказ.</p>
            </div>

            <div class="form-group">
                <label>Имя клиента</label>
                <input id="clientName" type="text" class="form-control" value="@Model.ClientName" />
            </div>

            <div class="form-group">
                <label>Телефон клиента</label>
                <input id="clientPhone" type="text" class="form-control" value="@Model.ClientPhone" />
            </div>

            <div class="form-group">
                <label>Комментарий клиента</label>
                <textarea readonly="readonly" rows="3" type="text" class="form-control">@Model.ClientComment</textarea>
                <p class="help-block">Какие-либо пожелания клиента.</p>
            </div>

            <div class="form-group">
                <label>Дата и время записи</label>
                <div class="input-append date">
                    <input id="appointedTime" readonly="readonly" style="background-color: #ffffff" class="form-control localdate" data-date="@Model.AppointedTime.ToString("O")" type="text">
                    <span class="add-on"><i class="icon-th"></i></span>
                </div>
            </div>

            <div class="form-group">
                <label>Ваш комментарий</label>
                <textarea id="masterComment" rows="3" type="text" class="form-control">@Model.MasterComment</textarea>
                <p class="help-block">Не обязательно к заполнению. Видно только для Вас.</p>
            </div>

            <button href="#" type="button" class="btn btn-success" id="saveBtn">
                <span class="glyphicon glyphicon-ok"></span> Сохранить
            </button>
        </form>
    </div>
</div>

src/MakeupStudio/Views/Orders/Index.cshtml
@{
    ViewBag.Title = "Новые заявки";
    Layout = "~/Views/Layouts/AdminLayout.cshtml";
}

@section scripts
{
    @Scripts.Render("~/bundles/scripts/orders/index")
}

<div style="max-width: 500px">
    @Html.Partial("~/Views/Partial/TempData.cshtml")
</div>

<p style="font-size: 17px">
    <span id="help-text"></span>
</p>

<div id="ordersTable"></div>

<script id="table-template" type="x-tmpl-mustache">
   {{#hasOrders}}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Дата заявки</th>
                <th>Имя клента</th>
                <th>Телефон клиента</th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            {{#orders}}
                <tr>
                    <td>{{toLocateDateTime}}</td>
                    <td>{{ClientName}}</td>
                    <td>{{ClientPhone}}</td>
                    <td>
                        <a href="/Orders/AppointMeeting?orderId={{Id}}" class="btn btn-success">
                            <span class="glyphicon glyphicon-ok"></span>
                            <span>Принять</span>
                        </a>
                        <button class="btn btn-danger remove-order-btn" data-id="{{Id}}">
                            <span class="glyphicon glyphicon-remove"></span>
                            <span>Удалить</span>
                        </button>
                    </td>
                </tr>
            {{/orders}}
        </tbody>
    </table>
    {{/hasOrders}}
</script>

src/MakeupStudio/Views/Orders/UpcomingOrders.cshtml
@model MakeupStudio.Core.Entities.Order[]

@{
    ViewBag.Title = "Заказы";
    Layout = "~/Views/Layouts/AdminLayout.cshtml";
}

@section scripts
{
    @Scripts.Render("~/bundles/scripts/orders/upcomingorders")
}

<a href="@Url.Action("Create", "Orders")" type="button" class="btn btn-success">
    Создать заказ
</a>

<p style="font-size: 17px">
    @if (Model.Length == 0)
    {
        <span id="help-text">У Вас нет заказов</span>
    }
</p>

<div style="max-width: 500px">
    @Html.Partial("~/Views/Partial/TempData.cshtml")
</div>

@if (Model.Length > 0)
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Время приема</th>
                <th>Имя клента</th>
                <th>Телефон клиента</th>
                <th></th>
            </tr>
        </thead>

        <tbody>
           @foreach (var order in Model)
           {
                <tr>
                    <td>
                        <span class="localdate" data-date="@order.AppointedTime.Value.ToString("O")">@order.AppointedTime.Value.ToString("O")</span>  
                    </td>
                    <td>@order.ClientName</td>
                    <td>@order.ClientPhone</td>
                    <td>
                        <button class="btn btn-success finishBtn" data-id="@order.Id">
                            <span>Выполнено</span>
                        </button>
                        <a href="@Url.Action("Edit", "Orders", new {orderId = order.Id})" class="btn btn-info" data-id="@order.Id">
                            <span>Изменить</span>
                        </a>
                        <button class="btn btn-danger remove-order-btn deleteOrder" data-id="@order.Id">
                            <span>Удалить</span>
                        </button>
                    </td>
                </tr>
           }
        </tbody>
    </table>
}